### ISSUE TITLE
undefined: common.StringToHash

### ISSUE THREAD

**Issue by coolhackboy** [duanbing/go-evm#3]
![image](https://user-images.githubusercontent.com/13427145/40575186-905fa404-6112-11e8-9db3-960b90f23bb0.png)

**Comment by duanbing** [comment]
Plz use `godep go run`. All the dependencies are maintained by `godep`.   Any good ideas are wellcome! 

I had deleted `main_getstate.go`,  everything was presented in `main.go`.   Just check it out!
